name: mind_up
description: A new Flutter project for Smart Learning.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Database (Offline)
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  
  # AI & Networking
  google_generative_ai: ^0.2.0
  http: ^1.1.0
  
  # UI Components
  table_calendar: ^3.0.9
  intl: ^0.19.0
  fl_chart: ^0.66.0 # For analytics
  google_fonts: ^6.1.0
  
  # Notifications & Background Work
  flutter_local_notifications: ^16.3.2
  workmanager: ^0.5.2
  
  # Voice
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.3
  
  # Utils
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  syncfusion_flutter_calendar: ^28.1.37

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
